services:
  # MariaDB Database Service
  mariadb:
    image: mariadb:10.6.4-focal
    container_name: mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      TZ: Europe/Warsaw
    expose:
      - 3306
      - 33060
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wordpressnet

  wordpress:
    image: wordpress:latest

    ports:
      - 8082:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpressnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      TZ: Europe/Warsaw
    ports:
      - "8081:80"
    depends_on:
      mariadb:
        condition: service_started
    networks:
      - wordpressnet


networks:
  wordpressnet:
    driver: bridge
    name: wordpress_bridge
    ipam:
      config:
        - subnet: 172.33.0.0/24


volumes:
  mariadb_data:
  wordpress_data:
